openapi: '3.0.1'
info:
  title: Livrotopia API
  description: API para gestão de livros e usuários no site Livrotopia.
  version: '0.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'

paths:
  /livros:
    get:
      summary: Listar livros disponíveis
      responses:
        '200':
          description: Lista de livros
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titulo:
                      type: string
                    autor:
                      type: string
                    genero:
                      type: string
                    descricao:
                      type: string
                    anoLancamento:
                      type: integer
                    preco:
                      type: number
                      format: float
                    capa:
                      type: string

    post:
      summary: Adicionar um novo livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: O título do livro.
                  example: "Diario de Anne Frank"
                autor:
                  type: string
                  description: O autor do livro.
                  example: "Anne Frank"
                genero:
                  type: string
                  description: O gênero do livro.
                  example: "Biografia"
                descricao:
                  type: string
                  description: A descrição do livro.
                  example: "Narrar momentos vivenciados pelo grupo de judeus confinados em um esconderijo durante a ocupação nazista dos Países Baixos."
                anoLancamento:
                  type: integer
                  description: O ano de lançamento do livro.
                  example: 1947
                preco:
                  type: number
                  format: float
                  description: O preço do livro em reais.
                  example: 39.90
                capa:
                  type: string
                  description: A URL da imagem da capa do livro.
                  example: "https://livraria.deiaetiba.com.br/image/cache/data/api/produtos/10984-515x800.jpg?1686834710"
      responses:
        '201':
          description: Livro criado com sucesso
        '400':
          description: Requisição inválida

  /livros/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Obter detalhes de um livro específico
      responses:
        '200':
          description: Livro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  titulo:
                    type: string
                  autor:
                    type: string
                  genero:
                    type: string
                  descricao:
                    type: string
                  anoLancamento:
                    type: integer
                  preco:
                    type: number
                    format: float
                  capa:
                    type: string
        '404':
          description: Livro não encontrado

    put:
      summary: Atualizar as informações de um livro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titulo:
                  type: string
                  description: O título do livro.
                  example: "Diario de Anne Frank"
                autor:
                  type: string
                  description: O autor do livro.
                  example: "Anne Frank"
                genero:
                  type: string
                  description: O gênero do livro.
                  example: "Biografia"
                descricao:
                  type: string
                  description: A descrição do livro.
                  example: "Narrar momentos vivenciados pelo grupo de judeus confinados em um esconderijo durante a ocupação nazista dos Países Baixos."
                anoLancamento:
                  type: integer
                  description: O ano de lançamento do livro.
                  example: 1947
                preco:
                  type: number
                  format: float
                  description: O preço do livro em reais.
                  example: 39.90
                capa:
                  type: string
                  description: A URL da imagem da capa do livro.
                  example: "https://livraria.deiaetiba.com.br/image/cache/data/api/produtos/10984-515x800.jpg?1686834710"
      responses:
        '200':
          description: Livro atualizado com sucesso
        '404':
          description: Livro não encontrado

    delete:
      summary: Remover um livro
      responses:
        '200':
          description: Livro removido com sucesso
        '404':
          description: Livro não encontrado

  /usuarios:
    get:
      summary: Listar usuários cadastrados
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                    email:
                      type: string

    post:
      summary: Registrar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "João Silva"
                email:
                  type: string
                  example: "joao.silva@exemplo.com"
                senha:
                  type: string
                  example: "senha123"
      responses:
        '201':
          description: Usuário registrado com sucesso
        '400':
          description: Erro ao registrar usuário

  /usuarios/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Obter detalhes de um usuário específico
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
        '404':
          description: Usuário não encontrado

    delete:
      summary: Remover um usuário
      responses:
        '200':
          description: Usuário removido com sucesso
        '404':
          description: Usuário não encontrado

  /usuarios/login:
    post:
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "joao.silva@exemplo.com"
                senha:
                  type: string
                  example: "senha123"
      responses:
        '200':
          description: Login bem-sucedido
        '401':
          description: Credenciais inválidas